server:
  port: 8080
spring:
  application:
    name: recharge
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/recharge
    username:
    password:
  liquibase:
    change-log: classpath:/db/changelog/changelog-recharge.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
    banner-mode: off